name: space-util
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - python=3.9.0
  - pip:
    - cloudant==2.14.0
    - numpy==1.19.4
    - pandas==1.1.4
    - python-dateutil==2.8.1
