name: dev-space-util
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.*
  - numpy=1.20.*
  - pandas=1.2.*
  - pip
  - pip:
    - folderstats==0.3.0
    - cloudant==2.14.0